### ISSUE TITLE
Editor does not work with IE11

### ISSUE THREAD

**Issue by ilkkalehtinen** [OpusCapita/react-crudeditor#240] opened 2018-02-19 14:08 UTC
Open with IE 11 page: https://opuscapita.github.io/react-crudeditor/branches/master/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false

=> No data is shown

**Comment by amourzenkov-sc** [comment] 2018-02-19 14:14
@kvolkovich-sc Probably duplicate of #13 "IE11 search view issue"

**Closed** 2018-02-19 14:18 UTC
Labels: closed/duplicate
